site_name: k8s笔记
nav:
    - Home: index.md
    - docker:
        - 概述: docker/overview.md
        - 安装: docker/install.md
        - 原理: docker/theory.md
        - 命令: docker/command.md
        - 问题解决: docker/solved.md
        - dockerfile: docker/dockerfile.md
    - k8s:
        - 组件说明: k8s/组件.md
        - pod概念: k8s/pod.md
        - 安装: k8s/安装.md
        - 配置: k8s/配置.md
        - 网络通讯: k8s/网络通讯.md
        - 资源控制器: k8s/资源控制器.md
        - DaemonSet: k8s/daemonset.md
        - Job: k8s/job.md
        - Service: k8s/service.md
        - Ingress: k8s/ingress.md
        - ConfigMap: k8s/configmap.md
        - Volume: k8s/volume.md
        - Secret: k8s/secret.md
        - PV: k8s/pv.md
        - 调度器: k8s/调度器.md
        - 安全认证: k8s/安全认证.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
